### ISSUE TITLE
Not possible to choose a specific server

### ISSUE THREAD

**Issue by mandre1904** [iobroker-community-adapters/ioBroker.web-speedy#1]
It´s not possible to choose a specific server. If you edit Results > server it will be overwritten after next update of Top 5 servers.

**Comment by DutchmanNL** [comment]
Thats as designed :-) this state Shows the Last Server tested

I can implement e new state, how would you like ?

Scan by id or url ?

Just for one run or permernantly

**Comment by DutchmanNL** [comment]
implement in 0.1.3 https://github.com/iobroker-community-adapters/ioBroker.web-speedy/commit/c83b39d9e6e8dec52a4a971a049efb7b3ecdc6c6

**Comment by mandre1904** [comment]
URL and permernantly. Please. ;)

**Comment by DutchmanNL** [comment]
url added in 0.1.6 https://github.com/iobroker-community-adapters/ioBroker.web-speedy/commit/091f7b66d71b809a82087aeddc119fcb23e9edd0
