### ISSUE TITLE
[Request] Start download, upload and ping test separately

### ISSUE THREAD

**Issue by xCruziX** [iobroker-community-adapters/ioBroker.web-speedy#3]
I would like to start the three processes separately, perhaps with 2 additional buttons

**Comment by DutchmanNL** [comment]
So like now a state to configure but instead of executing when I’d or URL’s inserted just by button push ?
I assume in addition a confirguration state what to use at auto test ?

**Comment by DutchmanNL** [comment]
sorry not implemented in library api https://github.com/ddsol/speedtest.net/issues/67
